;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	ac-js2-expand-function
	dabbrev-expand
	indent-for-tab-command
	tern-ac-dot-complete
	))

(setq mc/cmds-to-run-once
      '(
	keyboard-escape-quit
	))
