;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-brace
	c-electric-colon
	c-electric-paren
	c-electric-pound
	c-electric-semi&comma
	c-electric-slash
	c-electric-star
	c-toggle-electric-state
	comment-dwim
	dabbrev-expand
	downcase-region
	duplicate-line
	find-file
	helm-M-x
	hs-hide-block
	hs-show-block
	indent-for-tab-command
	jade-indent
	jade-newline-and-indent
	jade-unindent
	kill-region
	list-directory
	markdown-cycle
	markdown-enter-key
	markdown-exdent-or-delete
	org-return
	org-self-insert-command
	org-shiftright
	org-yank
	phi-search
	split-and-find-file-V
	tab-to-tab-stop
	tern-ac-dot-complete
	tern-rename-variable
	upcase-region
	yaml-electric-backspace
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	c-indent-line-or-region
	comment-region
	delete-window
	helm-swoop
	keyboard-escape-quit
	overwrite-mode
	split-and-find-file-H
	vim-prompt
	))
