(deftheme zerodark
  "Created 2019-03-13.")

(custom-theme-set-variables
 'zerodark
 '(ansi-color-names-vector ["#282c34" "#ff6c6b" "#98be65" "#da8548" "#61afef" "#c678dd" "#1f5582" "#abb2bf"]))

(custom-theme-set-faces
 'zerodark
 '(cursor ((((class color) (min-colors 89)) (:background "#abb2bf"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#24282f" :foreground "#687080"))))
 '(border ((((class color) (min-colors 89)) (:foreground "#3a3f4b"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#3a3f4b"))))
 '(highlight ((((class color) (min-colors 89)) (:background "#3e4451" :foreground "#abb2bf" :underline nil))))
 '(region ((((class color) (min-colors 89)) (:background "#3e4451" :foreground "#abb2bf"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#3e4451" :foreground "#abb2bf"))))
 '(isearch ((((class color) (min-colors 89)) (:background "#ddbd78" :foreground "#3e4451"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#666666" :foreground "#ddbd78"))))
 '(hl-line ((((class color) (min-colors 89)) (:background "#2c323b" :underline unspecified :inherit nil))))
 '(match ((((class color) (min-colors 89)) (:background "#3d4a41"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#61afef" :weight bold))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#687080" :slant italic))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#da8548" :weight bold))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#61afef"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#c678dd" :weight bold))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#98be65"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#9eac8c"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#61afef"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#61afef"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#ff6c6b" :weight bold :background "#4c3840"))))
 '(mode-line ((((class color) (min-colors 89)) (:background "#38394c" :height 0.9 :foreground "#61afef" :box (:line-width 6 :color "#38394c")))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:background "#22252c" :height 0.9 :foreground "#abb2bf" :box (:line-width 6 :color "#22252c")))))
 '(header-line ((((class color) (min-colors 89)) (:inherit mode-line-inactive))))
 '(error ((((class color) (min-colors 89)) (:foreground "#ff6c6b" :weight bold))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#da8548" :weight bold))))
 '(success ((((class color) (min-colors 89)) (:foreground "#98be65" :weight bold))))
 '(org-mode-line-clock ((((class color) (min-colors 89)) (:background unspecified (:inherit mode-line)))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#61afef" :weight bold))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#61afef" :weight bold))))
 '(line-number ((((class color) (min-colors 89)) (:foreground "#687080" :background "#282c34"))))
 '(line-number-current-line ((((class color) (min-colors 89)) (:foreground "#61afef" "#282c34" "#38394c"))))
 '(link ((((class color) (min-colors 89)) (:foreground "#61afef" :underline t))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#61afef" :underline t))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#3e4451" :box (:line-width 1 :color "#687080")))))
 '(widget-button ((((class color) (min-colors 89)) (:inherit link))))
 '(custom-button ((((class color) (min-colors 89)) (:background "#3a3f4b" :box (:line-width 2 :style released-button)))))
 '(custom-button-mouse ((((class color) (min-colors 89)) (:background "#3e4451" :box (:line-width 2 :style released-button)))))
 '(custom-button-pressed ((((class color) (min-colors 89)) (:background "#3e4451" :box (:line-width 2 :style pressed-button)))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:foreground "#c678dd" :weight bold :height 1.4))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:foreground "#c678dd" :weight bold))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#98be65"))))
 '(compilation-info ((((class color) (min-colors 89)) (:foreground "#c678dd" :weight bold))))
 '(compilation-warning ((((class color) (min-colors 89)) (:foreground "#da8548" :weight bold))))
 '(compilation-error ((((class color) (min-colors 89)) (:foreground "#ff6c6b" :weight bold))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#98be65" :weight bold))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "#98be65" :weight bold :inverse-video nil))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#da8548" :weight bold))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "#ff6c6b" :weight bold))))
 '(dired-header ((((class color) (min-colors 89)) (:foreground "#61afef" :background "#38394c" :weight bold))))
 '(dired-directory ((((class color) (min-colors 89)) (:foreground "#c678dd" :weight bold))))
 '(diff-removed ((((class color) (min-colors 89)) (:background "#4c3840" :foreground "#ff6c6b"))))
 '(diff-added ((((class color) (min-colors 89)) (:background "#3d4a41" :foreground "#98be65"))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:background "#38394c" :weight bold :foreground "#61afef"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:weight bold))))
 '(diff-header ((((class color) (min-colors 89)) (:background "#282c34" :foreground "#61afef"))))
 '(diff-context ((((class color) (min-colors 89)) (:foreground "#abb2bf"))))
 '(diff-refine-added ((((class color) (min-colors 89)) (:foreground "#98be65" :background "#3f6d54"))))
 '(diff-refine-removed ((((class color) (min-colors 89)) (:background "#744a5b" :foreground "#ff6c6b"))))
 '(magit-diff-context-highlight ((((class color) (min-colors 89)) (:background "#22252c"))))
 '(magit-diff-file-heading ((((class color) (min-colors 89)) (:weight bold :foreground "#61afef"))))
 '(magit-diff-file-heading-highlight ((((class color) (min-colors 89)) (:weight bold :foreground "#61afef" :background "#38394c"))))
 '(magit-diff-removed-highlight ((((class color) (min-colors 89)) (:inherit diff-removed))))
 '(magit-diff-removed ((((class color) (min-colors 89)) (:inherit diff-removed))))
 '(magit-diff-added-highlight ((((class color) (min-colors 89)) (:inherit diff-added))))
 '(magit-diff-added ((((class color) (min-colors 89)) (:inherit diff-added))))
 '(magit-diff-lines-heading ((((class color) (min-colors 89)) (:background "#1f5582" :foreground "white"))))
 '(magit-diff-hunk-heading ((((class color) (min-colors 89)) (:background "#3a3f4b"))))
 '(magit-diff-hunk-heading-highlight ((((class color) (min-colors 89)) (:background "#1f5582"))))
 '(magit-diff-hunk-heading ((((class color) (min-colors 89)) (:background "#3a3f4b"))))
 '(magit-process-ok ((((class color) (min-colors 89)) (:foreground "#98be65" :weight bold))))
 '(magit-section-highlight ((((class color) (min-colors 89)) (:background "#22252c"))))
 '(magit-section-heading ((((class color) (min-colors 89)) (:foreground "#cccccc" :weight bold))))
 '(magit-branch-current ((((class color) (min-colors 89)) (:foreground "#61afef" :background "#22252c" :box 1))))
 '(magit-branch-local ((((class color) (min-colors 89)) (:foreground "#c678dd" :background "#22252c" :box 1))))
 '(magit-branch-remote ((((class color) (min-colors 89)) (:foreground "#98be65" :background "#22252c" :box 1))))
 '(magit-reflog-reset ((((class color) (min-colors 89)) (:background "#4c3840" :foreground "#ff6c6b" :weight bold))))
 '(magit-reflog-amend ((((class color) (min-colors 89)) (:background "#38394c" :foreground "#61afef" :weight bold))))
 '(magit-reflog-rebase ((((class color) (min-colors 89)) (:background "#38394c" :foreground "#61afef" :weight bold))))
 '(magit-reflog-commit ((((class color) (min-colors 89)) (:background "#3d4a41" :foreground "#98be65" :weight bold))))
 '(magit-reflog-checkout ((((class color) (min-colors 89)) (:background "#4a473d" :foreground "#da8548" :weight bold))))
 '(magit-reflog-cherry-pick ((((class color) (min-colors 89)) (:background "#48384c" :foreground "#c678dd" :weight bold))))
 '(magit-bisect-bad ((((class color) (min-colors 89)) (:background "#4c3840" :foreground "#ff6c6b" :box 1))))
 '(magit-bisect-good ((((class color) (min-colors 89)) (:background "#38394c" :foreground "#61afef" :box 1))))
 '(magit-blame-heading ((((class color) (min-colors 89)) (:foreground "#98be65" :background "#3d4a41" :box 1))))
 '(git-commit-summary ((((class color) (min-colors 89)) (:weight bold))))
 '(magit-tag ((((class color) (min-colors 89)) (:foreground "#c678dd" :weight bold :box 1 :background "#202020"))))
 '(magit-sequence-part ((((class color) (min-colors 89)) (:foreground "#da8548" :weight bold))))
 '(magit-sequence-head ((((class color) (min-colors 89)) (:foreground "#98be65" :weight bold))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#61afef" :weight bold))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "#c678dd"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "#c678dd"))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "#98be65"))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "#c678dd"))))
 '(message-cited-text ((((class color) (min-colors 89)) (:foreground "#687080"))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#ff6c6b" :weight bold))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#c678dd" :weight bold))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#c678dd" :weight bold))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#61afef"))))
 '(company-preview ((((class color) (min-colors 89)) (:background "#22252c" :foreground "#abb2bf"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:background "#22252c" :foreground "#c678dd"))))
 '(company-preview-search ((((class color) (min-colors 89)) (:background "#61afef" :foreground "#abb2bf"))))
 '(company-tooltip ((((class color) (min-colors 89)) (:background "#22252c" :foreground "#abb2bf"))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:background "#22252c"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:background "#38394c"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:foreground "#c678dd" :weight bold :background "#22252c"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:foreground "#61afef" :weight bold :background "#38394c"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:foreground "#c678dd" :background "#3a3f4b" :weight bold))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:foreground "#abb2bf" :background "#3a3f4b"))))
 '(company-tooltip-mouse ((((class color) (min-colors 89)) (:foreground "#abb2bf" :background "#3a3f4b"))))
 '(js2-function-param ((((class color) (min-colors 89)) (:foreground "#61afef"))))
 '(js2-error ((((class color) (min-colors 89)) (:foreground "#ff6c6b"))))
 '(js2-jsdoc-html-tag-name ((((class color) (min-colors 89)) (:foreground "PeachPuff3"))))
 '(js2-jsdoc-html-tag-delimiter ((((class color) (min-colors 89)) (:foreground "PeachPuff3"))))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) (:foreground "#ff6c6b" :background "#4c3840" :weight bold :inverse-video t))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:background "#4a473d" :foreground "#da8548" :weight bold :inverse-video t))))
 '(flycheck-fringe-info ((((class color) (min-colors 89)) (:background "#38394c" :foreground "#61afef" :weight bold :inverse-video t))))
 '(flycheck-warning ((((class color) (min-colors 89)) (:underline (:color "#ff6c6b" :style wave)))))
 '(flycheck-error ((((class color) (min-colors 89)) (:underline (:color "#ff6c6b" :style wave)))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#282c34"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#ff6c6b" :background "#4c3840" :weight bold))))
 '(org-done ((((class color) (min-colors 89)) (:foreground "#61afef" :background "#38394c" :weight bold))))
 '(org-date ((((class color) (min-colors 89)) (:background "#3a3f4b"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#ff6c6b"))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#abb2bf"))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#da8548"))))
 '(org-headline-done ((((class color) (min-colors 89)) (:foreground "#687080"))))
 '(outline-1 ((((class color) (min-colors 89)) (:foreground "#61afef" :weight bold))))
 '(outline-2 ((((class color) (min-colors 89)) (:foreground "#c678dd" :weight bold))))
 '(outline-3 ((((class color) (min-colors 89)) (:foreground "PeachPuff3" :weight bold))))
 '(outline-4 ((((class color) (min-colors 89)) (:foreground "#9eac8c" :weight bold))))
 '(outline-5 ((((class color) (min-colors 89)) (:foreground "#61afef" :weight bold))))
 '(outline-6 ((((class color) (min-colors 89)) (:foreground "#c678dd" :weight bold))))
 '(outline-7 ((((class color) (min-colors 89)) (:foreground "PeachPuff3" :weight bold))))
 '(outline-8 ((((class color) (min-colors 89)) (:foreground "#9eac8c" :weight bold))))
 '(org-column-title ((((class color) (min-colors 89)) (:foreground unspecified :background unspecified))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#c678dd" :weight bold))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:foreground "#61afef" :weight bold :background "#38394c" :box 1))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#61afef" :weight bold))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#abb2bf" :weight bold))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#687080"))))
 '(org-time-grid ((((class color) (min-colors 89)) (:foreground "#687080"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#22252c"))))
 '(org-column-title ((((class color) (min-colors 89)) (:background "#38394c" :foreground "#61afef" :weight bold))))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:background "#3d4a41" :foreground "#9eac8c" :height 0.9))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:background "#3d4a41" :foreground "#9eac8c" :height 0.9))))
 '(gnus-group-news-1 ((((class color) (min-colors 89)) (:weight bold :foreground "#95e454"))))
 '(gnus-group-news-2 ((((class color) (min-colors 89)) (:weight bold :foreground "#cae682"))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:weight bold :foreground "#ccaa8f"))))
 '(gnus-group-news-4 ((((class color) (min-colors 89)) (:weight bold :foreground "#99968b"))))
 '(gnus-group-news-5 ((((class color) (min-colors 89)) (:weight bold :foreground "#cae682"))))
 '(gnus-group-news-low ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:weight bold :foreground "#95e454"))))
 '(gnus-group-mail-2 ((((class color) (min-colors 89)) (:weight bold :foreground "#cae682"))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:weight bold :foreground "#ccaa8f"))))
 '(gnus-group-mail-low ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(gnus-header-content ((((class color) (min-colors 89)) (:foreground "#8ac6f2"))))
 '(gnus-header-from ((((class color) (min-colors 89)) (:weight bold :foreground "#95e454"))))
 '(gnus-header-subject ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(gnus-header-name ((((class color) (min-colors 89)) (:foreground "#8ac6f2"))))
 '(gnus-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(which-func ((((class color) (min-colors 89)) (:foreground "#c678dd"))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:weight bold))))
 '(helm-header-line-left-margin ((((class color) (min-colors 89)) (:weight bold :foreground "#ff6c6b"))))
 '(helm-source-header ((((class color) (min-colors 89)) (:height 1.2 :weight bold :foreground "#61afef" :background "#38394c"))))
 '(helm-selection ((((class color) (min-colors 89)) (:background "#3a3f4b"))))
 '(helm-match ((((class color) (min-colors 89)) (:foreground "#c678dd" :background "#48384c" :weight bold))))
 '(helm-match-item ((((class color) (min-colors 89)) (:inherit isearch))))
 '(helm-M-x-key ((((class color) (min-colors 89)) (:foreground "#61afef" :weight bold :background "#38394c"))))
 '(helm-visible-mark ((((class color) (min-colors 89)) (:weight bold :foreground "#da8548" :background "#22252c"))))
 '(helm-prefarg ((((class color) (min-colors 89)) (:weight bold :foreground "#ff6c6b" :background "#4c3840"))))
 '(helm-separator ((((class color) (min-colors 89)) (:weight bold :foreground "#61afef"))))
 '(helm-grep-file ((((class color) (min-colors 89)) nil)))
 '(helm-grep-finish ((((class color) (min-colors 89)) (:foreground "#98be65"))))
 '(helm-grep-lineno ((((class color) (min-colors 89)) (:foreground "#61afef"))))
 '(helm-grep-match ((((class color) (min-colors 89)) (:foreground "#c678dd" :background "#48384c" :weight bold))))
 '(helm-moccur-buffer ((((class color) (min-colors 89)) nil)))
 '(helm-buffer-directory ((((class color) (min-colors 89)) (:foreground "#c678dd"))))
 '(helm-buffer-file ((((class color) (min-colors 89)) nil)))
 '(helm-buffer-process ((((class color) (min-colors 89)) (:foreground "#c678dd"))))
 '(helm-buffer-size ((((class color) (min-colors 89)) (:foreground "#61afef"))))
 '(helm-buffer-saved-out ((((class color) (min-colors 89)) (:foreground "#ff6c6b" :weight bold))))
 '(helm-ff-directory ((((class color) (min-colors 89)) (:foreground "#c678dd"))))
 '(helm-ff-dotted-directory ((((class color) (min-colors 89)) (:foreground "#c678dd"))))
 '(helm-ff-prefix ((((class color) (min-colors 89)) (:weight bold :foreground "#ff6c6b"))))
 '(helm-ff-file ((((class color) (min-colors 89)) nil)))
 '(helm-ff-executable ((((class color) (min-colors 89)) (:foreground "#98be65" :weight bold :background "#3d4a41"))))
 '(helm-ff-symlink ((((class color) (min-colors 89)) (:foreground "#da8548"))))
 '(helm-ff-invalid-symlink ((((class color) (min-colors 89)) (:foreground "#ff6c6b" :weight bold :background "#4c3840"))))
 '(helm-history-deleted ((((class color) (min-colors 89)) (:foreground "#ff6c6b" :weight bold :background "#4c3840"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:background "#1f5582"))))
 '(term-color-black ((((class color) (min-colors 89)) (:foreground "#abb2bf" :background "#22252c"))))
 '(term-color-red ((((class color) (min-colors 89)) (:foreground "#ff6c6b" :background "#4c3840"))))
 '(term-color-green ((((class color) (min-colors 89)) (:foreground "#98be65" :background "#3d4a41"))))
 '(term-color-yellow ((((class color) (min-colors 89)) (:foreground "#da8548" :background "#4a473d"))))
 '(term-color-blue ((((class color) (min-colors 89)) (:foreground "#61afef" :background "#38394c"))))
 '(term-color-magenta ((((class color) (min-colors 89)) (:foreground "#c678dd" :background "#48384c"))))
 '(term-color-cyan ((((class color) (min-colors 89)) (:foreground "#1f5582"))))
 '(term-color-white ((((class color) (min-colors 89)) (:foreground "#cccccc"))))
 '(term ((((class color) (min-colors 89)) (:foreground "#abb2bf" :background "#282c34"))))
 '(elfeed-search-date-face ((((class color) (min-colors 89)) (:foreground "#61afef"))))
 '(elfeed-search-feed-face ((((class color) (min-colors 89)) (:foreground "#61afef"))))
 '(elfeed-search-tag-face ((((class color) (min-colors 89)) (:foreground "#98be65"))))
 '(elfeed-search-title-face ((((class color) (min-colors 89)) (:foreground "#c678dd"))))
 '(anzu-replace-highlight ((((class color) (min-colors 89)) :foreground "#ff6c6b" :background "#4c3840" :strike-through t)))
 '(anzu-replace-to ((((class color) (min-colors 89)) :foreground "#98be65" :background "#3d4a41")))
 '(anzu-match-1 ((((class color) (min-colors 89)) :foreground "#ff6c6b" :background "#4c3840" :box t)))
 '(anzu-match-2 ((((class color) (min-colors 89)) :foreground "#ff6c6b" :background "#4c3840" :box t)))
 '(anzu-match-3 ((((class color) (min-colors 89)) :foreground "#ff6c6b" :background "#4c3840" :box t)))
 '(anzu-mode-line ((((class color) (min-colors 89)) :inherit mode-line :weight bold)))
 '(epa-validity-high ((((class color) (min-colors 89)) (:foreground "#98be65"))))
 '(epa-validity-low ((((class color) (min-colors 89)) (:foreground "#abb2bf"))))
 '(epa-validity-disabled ((((class color) (min-colors 89)) (:foreground "#ff6c6b" :weight bold :background "#4c3840"))))
 '(epa-field-name ((((class color) (min-colors 89)) (:foreground "#c678dd" :weight bold))))
 '(epa-field-body ((((class color) (min-colors 89)) (:foreground "#da8548"))))
 '(default ((((class color) (min-colors 89)) (:background "#282c34" :foreground "#abb2bf")))))

(provide-theme 'zerodark)
